const { VALID_ROLES_OBJECT } = require('../validations/auth/authValidations');

const CNIC_MAX_LENGTH = 15;
const CNIC_REGEX = /^\d{13}$/; // 13 digits
const CNIC_HYPHENATED_REGEX = /^\d{5}-\d{7}-\d{1}$/; // 5 digits - 7 digits - 1 digit

const TIME_REGEX = /^([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/; // HH:MM:SS or HH:MM format

const VALID_TABLES_OBJECT = {
    ADDRESS: 'address',
    CONTACT: 'contact',
    PERSON: 'person',
    TOKEN: 'token',
    PATIENT: 'patient',
    HOSPITAL: 'hospital',
    DOCTOR: 'doctor',
    APPOINTMENT: 'appointment',
    NOTIFICATION: 'notification',
    HOSPITAL_STAFF: 'hospital_staff',
    HOSPITAL_ASSOCIATION_REQUEST: 'hospital_association_request',
    INSURANCE_COMPANY: 'insurance_company',
    HOSPITAL_PANEL_LIST: 'hospital_panel_list',
    LAB_TEST: 'lab_test',
    EHR_ACCESS: 'ehr_access',
    LOG: 'log',
    SYSTEM_ADMIN: 'system_admin',
    MEDICINE: 'medicine',
    PRESCRIPTION: 'prescription',
    PATIENT_INSURANCE: 'patient_insurance',
    DOCUMENT: 'document',
    MEDICAL_CODER: 'medical_coder',
    PATIENT_ALLERGY: 'patient_allergy',
    PATIENT_FAMILY_HISTORY: 'patient_family_history',
    PATIENT_SURGICAL_HISTORY: 'patient_surgical_history',
    PATIENT_MEDICAL_HISTORY: 'patient_medical_history',
    ICD: 'icd',
    CPT: 'cpt',
    APPOINTMENT_ICD: 'appointment_icd',
    APPOINTMENT_CPT: 'appointment_cpt',
    BILL: 'bill'
};

const VALID_TABLES = Object.values(VALID_TABLES_OBJECT);

const NAME_MAX_LENGTH = 255;

const GENDER_MAX_LENGTH = 1;
const VALID_GENDERS = [
    'M',
    'F',
    'O'
];

const BLOOD_GROUP_MAX_LENGTH = 3;
const VALID_BLOOD_GROUPS = [
    'A+',
    'A-',
    'B+',
    'B-',
    'AB+',
    'AB-',
    'O+',
    'O-'
];

const DOCTOR_LICENSE_NUMBER_MAX_LENGTH = 10;
const DOCTOR_SPECIALIZATION_MAX_LENGTH = 255;
const DOCTOR_YEARS_OF_EXPERIENCE_MAX = 60;
const DOCTOR_STATUS_MAX_LENGTH = 10;
const VALID_DOCTOR_STATUSES_OBJECT = {
    ACTIVE: 'active',
    ON_LEAVE: 'on leave'
};
const VALID_DOCTOR_STATUSES = [
    VALID_DOCTOR_STATUSES_OBJECT.ACTIVE,
    VALID_DOCTOR_STATUSES_OBJECT.ON_LEAVE
];

const DOCUMENT_ORIGINAL_NAME_MAX_LENGTH = 255;
const DOCUMENT_FILE_NAME_MAX_LENGTH = 255;
const  DOCUMENT_MIME_TYPE_MAX_LENGTH = 255;
const UNVERIFIED_DOCUMENT_TYPE_MAX_LENGTH = 15;
const VALID_UNVERIFIED_DOCUMENT_TYPES_OBJECT = {
    PERSONAL: 'personal',
    LAB_TEST: 'lab test',
    PRESCRIPTION: 'prescription'
};
const VALID_UNVERIFIED_DOCUMENT_TYPES = [
    VALID_UNVERIFIED_DOCUMENT_TYPES_OBJECT.PERSONAL,
    VALID_UNVERIFIED_DOCUMENT_TYPES_OBJECT.LAB_TEST,
    VALID_UNVERIFIED_DOCUMENT_TYPES_OBJECT.PRESCRIPTION
];



const HOSPITAL_STAFF_ROLES_MAX_LENGTH = 30;
const VALID_HOSPITAL_STAFF_ROLES = [
    VALID_ROLES_OBJECT.HOSPITAL_ADMIN,
    VALID_ROLES_OBJECT.HOSPITAL_SUB_ADMIN,
    VALID_ROLES_OBJECT.HOSPITAL_FRONT_DESK,
    VALID_ROLES_OBJECT.HOSPITAL_LAB_TECHNICIAN,
    VALID_ROLES_OBJECT.HOSPITAL_PHARMACIST
];

const HOSPITAL_ASSOCIATION_REQUEST_ROLES_MAX_LENGTH = 15;
const VALID_HOSPITAL_ASSOCIATION_REQUEST_ROLES = [
    VALID_ROLES_OBJECT.DOCTOR,
    VALID_ROLES_OBJECT.MEDICAL_CODER
];

const EHR_ACCESS_STATUS_MAX_LENGTH = 20;
const VALID_EHR_ACCESS_STATUSES_OBJECT = {
    REQUESTED: 'requested',
    GRANTED: 'granted',
    DENIED: 'denied',
    REVOKED: 'revoked'
};
const VALID_EHR_ACCESS_STATUSES = [
    VALID_EHR_ACCESS_STATUSES_OBJECT.REQUESTED,
    VALID_EHR_ACCESS_STATUSES_OBJECT.GRANTED,
    VALID_EHR_ACCESS_STATUSES_OBJECT.DENIED,
    VALID_EHR_ACCESS_STATUSES_OBJECT.REVOKED
];

const LAB_TEST_NAME_MAX_LENGTH = 255;

const INSURANCE_COMPANY_NAME_MAX_LENGTH = 255;

const HOSPITAL_NAME_MAX_LENGTH = 255;
const FOCAL_PERSON_NAME_MAX_LENGTH = 255;
const FOCAL_PERSON_EMAIL_MAX_LENGTH = 255;
const FOCAL_PERSON_PHONE_MAX_LENGTH = 25;
const ORGANIZATION_ADDRESS_MAX_LENGTH = 500;

const INSURANCE_NUMBER_MIN_LENGTH = 9;
const INSURANCE_NUMBER_MAX_LENGTH = 13;
const INSURANCE_POLICY_HOLDER_NAME_MAX_LENGTH = 255;
const INSURANCE_RELATION_TO_HOLDER_MAX_LENGTH = 10;
const VALID_INSURANCE_RELATION_TO_HOLDER_OBJECT = {
    SELF: 'self',
    SPOUSE: 'spouse',
    CHILD: 'child',
    PARENT: 'parent'
};
const VALID_INSURANCE_RELATION_TO_HOLDER = [
    VALID_INSURANCE_RELATION_TO_HOLDER_OBJECT.SELF,
    VALID_INSURANCE_RELATION_TO_HOLDER_OBJECT.SPOUSE,
    VALID_INSURANCE_RELATION_TO_HOLDER_OBJECT.CHILD,
    VALID_INSURANCE_RELATION_TO_HOLDER_OBJECT.PARENT
];

const CLAIM_STATUS_MAX_LENGTH = 10;
const VALID_CLAIM_STATUSES_OBJECT = {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected'
};
const VALID_CLAIM_STATUSES = [
    VALID_CLAIM_STATUSES_OBJECT.PENDING,
    VALID_CLAIM_STATUSES_OBJECT.APPROVED,
    VALID_CLAIM_STATUSES_OBJECT.REJECTED
];

module.exports = {
    CNIC_MAX_LENGTH,
    CNIC_REGEX,
    CNIC_HYPHENATED_REGEX,
    TIME_REGEX,
    VALID_TABLES_OBJECT,
    VALID_TABLES,
    NAME_MAX_LENGTH,
    GENDER_MAX_LENGTH,
    VALID_GENDERS,
    BLOOD_GROUP_MAX_LENGTH,
    VALID_BLOOD_GROUPS,
    DOCTOR_LICENSE_NUMBER_MAX_LENGTH,
    DOCTOR_SPECIALIZATION_MAX_LENGTH,
    DOCTOR_YEARS_OF_EXPERIENCE_MAX,
    DOCTOR_STATUS_MAX_LENGTH,
    VALID_DOCTOR_STATUSES_OBJECT,
    VALID_DOCTOR_STATUSES,
    DOCUMENT_ORIGINAL_NAME_MAX_LENGTH,
    DOCUMENT_FILE_NAME_MAX_LENGTH,
    DOCUMENT_MIME_TYPE_MAX_LENGTH,
    UNVERIFIED_DOCUMENT_TYPE_MAX_LENGTH,
    VALID_UNVERIFIED_DOCUMENT_TYPES_OBJECT,
    VALID_UNVERIFIED_DOCUMENT_TYPES,
    HOSPITAL_STAFF_ROLES_MAX_LENGTH,
    VALID_HOSPITAL_STAFF_ROLES,
    HOSPITAL_ASSOCIATION_REQUEST_ROLES_MAX_LENGTH,
    VALID_HOSPITAL_ASSOCIATION_REQUEST_ROLES,
    EHR_ACCESS_STATUS_MAX_LENGTH,
    VALID_EHR_ACCESS_STATUSES_OBJECT,
    VALID_EHR_ACCESS_STATUSES,
    LAB_TEST_NAME_MAX_LENGTH,
    INSURANCE_COMPANY_NAME_MAX_LENGTH,
    HOSPITAL_NAME_MAX_LENGTH,
    FOCAL_PERSON_NAME_MAX_LENGTH,
    FOCAL_PERSON_EMAIL_MAX_LENGTH,
    FOCAL_PERSON_PHONE_MAX_LENGTH,
    ORGANIZATION_ADDRESS_MAX_LENGTH,
    INSURANCE_NUMBER_MIN_LENGTH,
    INSURANCE_NUMBER_MAX_LENGTH,
    INSURANCE_POLICY_HOLDER_NAME_MAX_LENGTH,
    INSURANCE_RELATION_TO_HOLDER_MAX_LENGTH,
    VALID_INSURANCE_RELATION_TO_HOLDER_OBJECT,
    VALID_INSURANCE_RELATION_TO_HOLDER,
    CLAIM_STATUS_MAX_LENGTH,
    VALID_CLAIM_STATUSES_OBJECT,
    VALID_CLAIM_STATUSES
};