require("dotenv").config();

const PROJECT_BACKEND_BASE_URL = process.env.PROJECT_BACKEND_BASE_URL;

const PROJECT_BACKEND_UPDATE_CLAIM_STATUS_ENDPOINT = process.env.PROJECT_BACKEND_UPDATE_CLAIM_STATUS_ENDPOINT;

const PROJECT_BACKEND_INSERT_INSURANCE_COMPANY_ENDPOINT = process.env.PROJECT_BACKEND_INSERT_INSURANCE_COMPANY_ENDPOINT;

const PROJECT_BACKEND_UPDATE_INSURANCE_COMPANY_ENDPOINT = process.env.PROJECT_BACKEND_UPDATE_INSURANCE_COMPANY_ENDPOINT;
const INTERSYSTEM_SYNC_SECRET = process.env.INTERSYSTEM_SYNC_SECRET || "local-sync-secret";

module.exports = {
    PROJECT_BACKEND_BASE_URL,
    PROJECT_BACKEND_UPDATE_CLAIM_STATUS_ENDPOINT,
    PROJECT_BACKEND_INSERT_INSURANCE_COMPANY_ENDPOINT,
    PROJECT_BACKEND_UPDATE_INSURANCE_COMPANY_ENDPOINT,
    INTERSYSTEM_SYNC_SECRET,
};