const CNIC_MAX_LENGTH = 15;
const CNIC_REGEX = /^\d{13}$/; // 13 digits
const CNIC_HYPHENATED_REGEX = /^\d{5}-\d{7}-\d{1}$/; // 5 digits - 7 digits - 1 digit

const NAME_MAX_LENGTH = 255;

const HOSPITAL_NAME_MAX_LENGTH = 255;

const INSURANCE_COMPANY_NAME_MAX_LENGTH = 255;
const FOCAL_PERSON_NAME_MAX_LENGTH = 255;
const FOCAL_PERSON_EMAIL_MAX_LENGTH = 255;
const FOCAL_PERSON_PHONE_MAX_LENGTH = 25;
const ORGANIZATION_ADDRESS_MAX_LENGTH = 500;

const VALID_ROLES_OBJECT = {
    SUPER_ADMIN: "super admin",
    INSURANCE_ADMIN: "insurance admin",
    INSURANCE_SUB_ADMIN: "insurance sub admin"
}

const VALID_ROLES_FOR_SIGN_IN = [
    VALID_ROLES_OBJECT.SUPER_ADMIN,
    VALID_ROLES_OBJECT.INSURANCE_ADMIN,
    VALID_ROLES_OBJECT.INSURANCE_SUB_ADMIN
];

const INSURANCE_STAFF_ROLES_MAX_LENGTH = 20;
const VALID_INSURANCE_STAFF_ROLES = [
    VALID_ROLES_OBJECT.INSURANCE_ADMIN,
    VALID_ROLES_OBJECT.INSURANCE_SUB_ADMIN
];

const INSURANCE_PLAN_NAME_MAX_LENGTH = 255;

const INSURANCE_NUMBER_MIN_LENGTH = 9;
const INSURANCE_NUMBER_MAX_LENGTH = 13;
const INSURANCE_POLICY_HOLDER_NAME_MAX_LENGTH = 255;

const PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_MAX_LENGTH = 10;
const VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_OBJECT = {
    SELF: "self",
    SPOUSE: "spouse",
    CHILD: "child",
    PARENT: "parent"
};
const VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER = [
    VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_OBJECT.SELF,
    VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_OBJECT.SPOUSE,
    VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_OBJECT.CHILD,
    VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_OBJECT.PARENT
];

module.exports = {
    CNIC_MAX_LENGTH,
    CNIC_REGEX,
    CNIC_HYPHENATED_REGEX,
    NAME_MAX_LENGTH,
    HOSPITAL_NAME_MAX_LENGTH,
    INSURANCE_COMPANY_NAME_MAX_LENGTH,
    FOCAL_PERSON_NAME_MAX_LENGTH,
    FOCAL_PERSON_EMAIL_MAX_LENGTH,
    FOCAL_PERSON_PHONE_MAX_LENGTH,
    ORGANIZATION_ADDRESS_MAX_LENGTH,
    VALID_ROLES_OBJECT,
    VALID_ROLES_FOR_SIGN_IN,
    INSURANCE_STAFF_ROLES_MAX_LENGTH,
    VALID_INSURANCE_STAFF_ROLES,
    INSURANCE_PLAN_NAME_MAX_LENGTH,
    INSURANCE_NUMBER_MIN_LENGTH,
    INSURANCE_NUMBER_MAX_LENGTH,
    INSURANCE_POLICY_HOLDER_NAME_MAX_LENGTH,
    PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_MAX_LENGTH,
    VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER_OBJECT,
    VALID_PERSON_INSURANCE_RELATIONSHIP_TO_HOLDER
};