const { pool } = require("../config/databaseConfig");
const { addressTableQuery } = require("./address/addressTableQuery");
const { personTableQuery } = require("./person/personTableQuery");
const { contactTableQuery } = require("./contact/contactTableQuery");
const { personContactTableQuery } = require("./person/personContactTableQuery");
const { emailVerificationTokenTableQuery } = require("./token/emailVerificationTokenTableQuery");
const { passwordResetTokenTableQuery } = require("./token/passwordResetTokenTableQuery");
const { patientTableQuery } = require("./patient/patientTableQuery");
const { hospitalTableQuery } = require("./hospital/hospitalTableQuery");
const { doctorTableQuery } = require("./doctor/doctorTableQuery");
const { appointmentRequestTableQuery } = require("./appointment/appointmentRequestTableQuery");
const { appointmentTableQuery } = require("./appointment/appointmentTableQuery");
const { doctorNoteTableQuery } = require("./doctor/doctorNoteTableQuery");
const { icdTableQuery } = require("./medicalCoding/icdTableQuery");
const { cptTableQuery } = require("./medicalCoding/cptTableQuery");
const { modifierTableQuery } = require("./medicalCoding/modifierTableQuery");
const { medicalCodingTableQuery } = require("./medicalCoding/medicalCodingTableQuery");
const { notificationTableQuery } = require("./notification/notificationTableQuery");
const { labTestTableQuery } = require("./labTest/labTestTableQuery");
const { unverifiedDocumentTableQuery } = require("./document/unverifiedDocumentTableQuery");
const { verifiedDocumentTableQuery } = require("./document/verifiedDocumentTableQuery");
const { logTableQuery } = require("./log/logTableQuery");
const { EHRAccessTable } = require("./EHR/EHRAccessTableQuery");
const { EHRAccessRequestTable } = require("./EHR/EHRAccessRequestTableQuery");
const { insuranceCompanyTableQuery } = require("./insurance/insuranceCompanyTableQuery");
const { systemAdminTableQuery } = require("./system/systemAdminTableQuery");
const { hospitalStaffTableQuery } = require("./hospital/hospitalStaffTableQuery");
const { medicineTableQuery } = require("./medicine/medicineTableQuery");
const { prescriptionTableQuery } = require("./prescription/prescriptionTableQuery");
const { hospitalAssociationRequestTableQuery } = require("./hospital/hospitalAssociationRequestTableQuery");
const { insuranceTableQuery } = require("./insurance/insuranceTableQuery");
const { patientInsuranceTableQuery } = require("./patient/patientInsuranceTableQuery");
const { hospitalPanelListTableQuery } = require("./hospital/hospitalPanelListTableQuery");

const database = async () => {
    try {
        await pool.query(addressTableQuery);
        console.log("Address Table Initialized");
        await pool.query(personTableQuery);
        console.log("Person Table Initialized");
        await pool.query(contactTableQuery);
        console.log("Contact Table Initialized");
        await pool.query(personContactTableQuery);
        console.log("Person Contact Table Initialized");
        await pool.query(emailVerificationTokenTableQuery);
        console.log("Email Verification Token Table Initialized");
        await pool.query(passwordResetTokenTableQuery);
        console.log("Password Reset Token Table Initialized");
        await pool.query(patientTableQuery);
        console.log("Patient Table Initialized");
        await pool.query(hospitalTableQuery);
        console.log("Hospital Table Initialized");
        await pool.query(doctorTableQuery);
        console.log("Doctor Table Initialized");
        await pool.query(appointmentRequestTableQuery);
        console.log("Appointment Request Table Initialized");
        await pool.query(appointmentTableQuery);
        console.log("Appointment Table Initialized");
        await pool.query(doctorNoteTableQuery);
        console.log("Doctor Note Table Initialized");
        await pool.query(icdTableQuery);
        console.log("ICD Table Initialized");
        await pool.query(cptTableQuery);
        console.log("CPT Table Initialized");
        await pool.query(modifierTableQuery);
        console.log("Modifier Table Initialized");
        await pool.query(medicalCodingTableQuery);
        console.log("Medical Coding Table Initialized");
        await pool.query(notificationTableQuery);
        console.log("Notification Table Initialized");
        await pool.query(labTestTableQuery);
        console.log("Lab Test Table Initialized");
        await pool.query(unverifiedDocumentTableQuery);
        console.log("Unverified Document Table Initialized");
        await pool.query(verifiedDocumentTableQuery);
        console.log("Verified Document Table Initialized");
        await pool.query(logTableQuery);
        console.log("Log Table Initialized");
        await pool.query(EHRAccessRequestTable);
        console.log("EHR Access Request Table Initialized");
        await pool.query(EHRAccessTable);
        console.log("EHR Access Table Initialized");
        await pool.query(insuranceCompanyTableQuery);
        console.log("Insurance Company Table Initialized");
        await pool.query(systemAdminTableQuery);
        console.log("System Admin Table Initialized");
        await pool.query(hospitalStaffTableQuery);
        console.log("Hospital Staff Table Initialized");
        await pool.query(labTestTableQuery);
        console.log("Lab Test Table Initialized");
        await pool.query(medicineTableQuery);
        console.log("Medicine Table Initialized");
        await pool.query(prescriptionTableQuery);
        console.log("Prescription Table Initialized");
        await pool.query(hospitalAssociationRequestTableQuery);
        console.log("Hospital Association Request Table Initialized");
        await pool.query(insuranceTableQuery);
        console.log("Insurance Table Initialized");
        await pool.query(patientInsuranceTableQuery);
        console.log("Patient Insurance Table Initialized");
        await pool.query(hospitalPanelListTableQuery);
        console.log("Hospital Panel List Table Initialized");

        console.log("Database Initialized Successfully");
    } catch (error) {
        console.log(`Error Initializing Database: ${error.message}`);
    }
};

module.exports = { database };