require("dotenv").config();

const AI_MEDICAL_CODING_API_BASE_URL = process.env.AI_MEDICAL_CODING_API_BASE_URL;

const AI_MEDICAL_CODING_GENERATE_CODES_ENDPOINT = process.env.AI_MEDICAL_CODING_GENERATE_CODES_ENDPOINT;

module.exports = {
    AI_MEDICAL_CODING_API_BASE_URL,
    AI_MEDICAL_CODING_GENERATE_CODES_ENDPOINT,
};