require("dotenv").config();

const INSURANCE_BACKEND_BASE_URL = process.env.INSURANCE_BACKEND_BASE_URL;

const INSURANCE_BACKEND_VERIFY_INSURANCE_ENDPOINT = process.env.INSURANCE_BACKEND_VERIFY_INSURANCE_ENDPOINT;

const INSURANCE_BACKEND_SEND_CLAIM_ENDPOINT = process.env.INSURANCE_BACKEND_SEND_CLAIM_ENDPOINT;

const INSURANCE_BACKEND_INSERT_HOSPITAL_ENDPOINT = process.env.INSURANCE_BACKEND_INSERT_HOSPITAL_ENDPOINT;

const INSURANCE_BACKEND_UPDATE_HOSPITAL_ENDPOINT = process.env.INSURANCE_BACKEND_UPDATE_HOSPITAL_ENDPOINT;
const INTERSYSTEM_SYNC_SECRET = process.env.INTERSYSTEM_SYNC_SECRET || "local-sync-secret";

module.exports = {
    INSURANCE_BACKEND_BASE_URL, INSURANCE_BACKEND_VERIFY_INSURANCE_ENDPOINT,
    INSURANCE_BACKEND_SEND_CLAIM_ENDPOINT, INSURANCE_BACKEND_INSERT_HOSPITAL_ENDPOINT,
    INSURANCE_BACKEND_UPDATE_HOSPITAL_ENDPOINT,
    INTERSYSTEM_SYNC_SECRET,
};